
package com.bdoc.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "BDocResourceException", targetNamespace = "http://service.bdoc.com/")
public class BDocResourceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BDocResourceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BDocResourceException_Exception(String message, BDocResourceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BDocResourceException_Exception(String message, BDocResourceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bdoc.service.BDocResourceException
     */
    public BDocResourceException getFaultInfo() {
        return faultInfo;
    }

}
