
package com.bdoc.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BdocWebWSService", targetNamespace = "http://service.bdoc.com/", wsdlLocation = "file:/C:/Workspace/bdocweb-ws-5.0/WebContent/wsdl/BdocWebWSService.wsdl")
public class BdocWebWSService
    extends Service
{

    private final static URL BDOCWEBWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.bdoc.service.BdocWebWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.bdoc.service.BdocWebWSService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Workspace/bdocweb-ws-5.0/WebContent/wsdl/BdocWebWSService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Workspace/bdocweb-ws-5.0/WebContent/wsdl/BdocWebWSService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BDOCWEBWSSERVICE_WSDL_LOCATION = url;
    }

    public BdocWebWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BdocWebWSService() {
        super(BDOCWEBWSSERVICE_WSDL_LOCATION, new QName("http://service.bdoc.com/", "BdocWebWSService"));
    }

    /**
     * 
     * @return
     *     returns BdocWebWS
     */
    @WebEndpoint(name = "BdocWebWSPort")
    public BdocWebWS getBdocWebWSPort() {
        return super.getPort(new QName("http://service.bdoc.com/", "BdocWebWSPort"), BdocWebWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BdocWebWS
     */
    @WebEndpoint(name = "BdocWebWSPort")
    public BdocWebWS getBdocWebWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.bdoc.com/", "BdocWebWSPort"), BdocWebWS.class, features);
    }

}
