
package com.bdoc.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "BDocNetworkException", targetNamespace = "http://service.bdoc.com/")
public class BDocNetworkException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BDocNetworkException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BDocNetworkException_Exception(String message, BDocNetworkException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BDocNetworkException_Exception(String message, BDocNetworkException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bdoc.service.BDocNetworkException
     */
    public BDocNetworkException getFaultInfo() {
        return faultInfo;
    }

}
