
package com.bdoc.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BdocWebWS", targetNamespace = "http://service.bdoc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BdocWebWS {


    /**
     * 
     * @return
     *     returns java.util.List<com.bdoc.service.Domain>
     * @throws BDocNetworkException_Exception
     * @throws BDocWebException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRepository", targetNamespace = "http://service.bdoc.com/", className = "com.bdoc.service.GetRepository")
    @ResponseWrapper(localName = "getRepositoryResponse", targetNamespace = "http://service.bdoc.com/", className = "com.bdoc.service.GetRepositoryResponse")
    public List<Domain> getRepository()
        throws BDocNetworkException_Exception, BDocWebException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.bdoc.service.TemplateInfos
     * @throws BDocNetworkException_Exception
     * @throws BDocWebException_Exception
     * @throws BDocResourceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTemplate", targetNamespace = "http://service.bdoc.com/", className = "com.bdoc.service.GetTemplate")
    @ResponseWrapper(localName = "getTemplateResponse", targetNamespace = "http://service.bdoc.com/", className = "com.bdoc.service.GetTemplateResponse")
    public TemplateInfos getTemplate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws BDocNetworkException_Exception, BDocResourceException_Exception, BDocWebException_Exception
    ;

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns com.bdoc.service.InteractionResult
     * @throws BDocNetworkException_Exception
     * @throws BDocWebException_Exception
     * @throws BDocResourceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generation", targetNamespace = "http://service.bdoc.com/", className = "com.bdoc.service.Generation")
    @ResponseWrapper(localName = "generationResponse", targetNamespace = "http://service.bdoc.com/", className = "com.bdoc.service.GenerationResponse")
    public InteractionResult generation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        List<MapItem> arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        byte[] arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        List<Integer> arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        List<MapItem> arg6)
        throws BDocNetworkException_Exception, BDocResourceException_Exception, BDocWebException_Exception
    ;

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.bdoc.service.InteractionResult
     * @throws BDocNetworkException_Exception
     * @throws BDocWebException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateTextForm", targetNamespace = "http://service.bdoc.com/", className = "com.bdoc.service.ValidateTextForm")
    @ResponseWrapper(localName = "validateTextFormResponse", targetNamespace = "http://service.bdoc.com/", className = "com.bdoc.service.ValidateTextFormResponse")
    public InteractionResult validateTextForm(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        ValidationType arg5)
        throws BDocNetworkException_Exception, BDocWebException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.bdoc.service.InteractionResult
     * @throws BDocNetworkException_Exception
     * @throws BDocWebException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateDataForm", targetNamespace = "http://service.bdoc.com/", className = "com.bdoc.service.ValidateDataForm")
    @ResponseWrapper(localName = "validateDataFormResponse", targetNamespace = "http://service.bdoc.com/", className = "com.bdoc.service.ValidateDataFormResponse")
    public InteractionResult validateDataForm(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<MapItem> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        ValidationType arg3)
        throws BDocNetworkException_Exception, BDocWebException_Exception
    ;

}
